### ISSUE TITLE
Reason sometimes empty

### ISSUE THREAD

**Issue by Mooseman0** [AWegnerGitHub/SE_Zephyr_VoteRequest_bot#22]
[Triggered](http://chat.stackoverflow.com/transcript/message/20700897#20700897):

>`[tag:cv-plz] http://stackoverflow.com/questions/27669972/folder-structure-of-a-smacss-project-where-to-put-class (opinionated)`

[Reflected](http://chat.meta.stackexchange.com/transcript/message/2842870#2842870):

>`**Close Vote Request** for stackoverflow.com/questions/… by cimmanon from HTML / CSS / WebDesign Reason:`

Issue: `Reason:` should not be present because it is empty.

**Comment by AWegnerGitHub** [comment]
Has this happened recently? I haven't been able to replicate it on any of my tests.

**Comment by Mooseman0** [comment]
@AWegnerGitHub I have not seen this issue again, no.
