### ISSUE TITLE
Zephyr does not parse SOCVR-formatted reasons correctly.

### ISSUE THREAD

**Issue by JC3** [AWegnerGitHub/SE_Zephyr_VoteRequest_bot#36]
Example 1:

> [[tag:cv-pls] [tag:c++] duplicate Unusual std::vector::size() response - NateM‎ - 2017-03-13 02:47:51Z](http://chat.stackoverflow.com/transcript/message/36080875#36080875)

(Reported via SECVRG) Yields:

> [Close Vote Request for stackoverflow.com/q/42755902/… by Jason C from SO Close Vote Reviewers](http://chat.meta.stackexchange.com/transcript/message/5847650#5847650)

No reason parsed at all.

---

Example 2:

> [[tag:cv-pls] [tag:mysql] stackoverflow.com/questions/… - duplicate (can't modify table being selected from)](http://chat.stackoverflow.com/transcript/message/36080347#36080347)

Yields:

> [Close Vote Request for stackoverflow.com/questions/… by Shadow from SO Close Vote Reviewers Reason: [tag:mysql]](http://chat.meta.stackexchange.com/transcript/message/5847390#5847390)

---

Etc. Of particular difficulty seems to be SOCVR's practice of including additional tags after the request tag. The reason-after-link in example 2 is a bit of an edge case but could theoretically be supported as well with some effort.

Zephyr should probably at least support SOCVR's preferred format (which I would link to but the socvr.org domain is down at the moment, doh), given the number of requests that originate from there.

Alternatively: Discard all tags and user profile links (present in [automated reports](http://chat.stackoverflow.com/transcript/message/36081033#36081033)), then parse [first](http://chat.stackoverflow.com/transcript/message/36081020#36081020) link as the question and everything else as the reason. This would cover example 2 as well, although it would be sloppy with timestamps -- but something along those lines.

**Comment by AWegnerGitHub** [comment]
Zephyr has been offline for almost 18 months at this point. I don't plan on reactivating it, so I'm going to close this.
